repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: check-case-conflict
      - id: check-added-large-files
        args: [--maxkb=1024, --enforce-all]
      - id: no-commit-to-branch
        args: [--branch, main, --branch, dev]
